import type { Metadata } from "next";
import { Inter, Noto_Sans_Lao } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const natoLaos = Noto_Sans_Lao({
  subsets: ['lao'],
  weight: ['400','700'],
  variable:"--font-noto-lao"

})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${natoLaos.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
